apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argo-nginx
  namespace: argo
spec:
  ingressClassName: nginx
  rules:
  - host: argo-nginx.videoconferenciaclaro.com
    http:
      paths:
      - backend:
          service:
            name: nginx-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - argo-nginx.videoconferenciaclaro.com
    secretName: tls-videoconferenciaclaro
